lib/naive_dice_web/router.ex
defmodule NaiveDiceWeb.Router do
  use NaiveDiceWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", NaiveDiceWeb do
    pipe_through :browser

    get "/", EventController, :index

    resources("/events", EventController, only: [:index, :show]) do
      resources("/tickets", TicketController, only: [:new, :create])
    end

    # event_id is captured on a Ticket already - no need to have it in a route
    resources("/tickets", TicketController, only: [:edit, :show])
    get("/ticket/:id/update", TicketController, :update)
    get("/ticket/:id/cancel", TicketController, :cancel)

    resources("/guests", GuestController, only: [:index])
    delete "/guests/reset", GuestController, :reset_guests
  end

  # Other scopes may use custom stacks.
  # scope "/api", NaiveDiceWeb do
  #   pipe_through :api
  # end
end

lib/naive_dice/events/ticket.ex
defmodule NaiveDice.Events.Ticket do
  @moduledoc """
  This schema represents a purchased ticket

  TODO: should we use the same schema to represent a pending reservation?
  """

  use Ecto.Schema
  import Ecto.Changeset

  # TODO: the schema is far from beging complete:
  schema "tickets" do
    field :user_name, :string
    field :confirmed, :boolean
    field :payment_id, :string
    belongs_to :event, NaiveDice.Events.Event

    timestamps()
  end

  @spec changeset(
          {map, map}
          | %{
              :__struct__ => atom | %{:__changeset__ => map, optional(any) => any},
              optional(atom) => any
            },
          :invalid | %{optional(:__struct__) => none, optional(atom | binary) => any}
        ) :: Ecto.Changeset.t()
  @doc false
  def changeset(ticket, attrs \\ %{}) do
    ticket
    |> cast(attrs, [:user_name, :confirmed, :payment_id])
    |> unique_constraint(:user_name)
    |> maybe_put_assoc(:event, attrs[:event])
    |> validate_required([:user_name, :event])
  end

  defp maybe_put_assoc(ticket, :event, nil), do: ticket
  defp maybe_put_assoc(ticket, :event, event), do: put_assoc(ticket, :event, event)
end

lib/naive_dice/events/tickets.ex
defmodule NaiveDice.Tickets do
  import Ecto.Query
  alias NaiveDice.Events.Ticket
  alias NaiveDice.Repo
  alias Ecto.Multi

  # My TODO: Separate functions of ticket and event into different modules

  def get_by_payment_id(id) do
    Repo.get_by(Ticket, payment_id: id)
  end

  def confirm_paid_ticket(ticket) do
    Multi.new()
    |> Multi.run(:check_available_tickets, fn repo, _ ->
      has_available_tickets?(repo, ticket.event)
    end)
    |> Multi.update(:ticket, Ticket.changeset(ticket, %{confirmed: true}))
    |> Repo.transaction()
    |> cancel_stale_ticket_removal()
  end

  defp cancel_stale_ticket_removal({:ok, %{ticket: ticket}} = params) do
    NaiveDice.TicketScheduler.Supervisor.terminate_child_by_id(ticket.id)
    params
  end

  defp cancel_stale_ticket_removal(params), do: params

  def update_payment_id(ticket, payment_id) do
    ticket
    |> Ticket.changeset(%{payment_id: payment_id})
    |> Repo.update()
  end

  def get_guests() do
    from(
      t in Ticket,
      where: t.confirmed == true,
      select: t.user_name
    )
    |> Repo.all()
  end

  def new_ticket_changeset(event) do
    Ticket.changeset(%Ticket{}, %{event: event})
  end

  def available_tickets(repo, event) do
    from(
      t in Ticket,
      where: t.event_id == ^event.id and t.confirmed == true,
      select: count(t.id)
    )
    |> repo.one()
  end

  def is_pending_ticket?(repo, ticket) do
    result =
      from(
        t in Ticket,
        where: t.id == ^ticket.id and t.confirmed == false,
        select: count(t.id)
      )
      |> repo.one()

    if result == 1, do: {:ok, result}, else: {:error, result}
  end

  def has_available_tickets?(repo, event) do
    allocation = available_tickets(repo, event)

    if allocation >= 5, do: {:error, allocation}, else: {:ok, allocation}
  end

  def reserve_ticket(event, user_name) do
    Multi.new()
    |> Multi.run(:check_available_tickets, fn repo, _ -> has_available_tickets?(repo, event) end)
    |> Multi.insert(
      :create_ticket,
      Ticket.changeset(%Ticket{}, %{user_name: user_name, event: event})
    )
    |> Repo.transaction()
  end

  def delete_pending_ticket(ticket) do
    Multi.new()
    |> Multi.run(:check_pending, fn repo, _ -> is_pending_ticket?(repo, ticket) end)
    |> Multi.delete(:delete_ticket, ticket)
    |> Repo.transaction()
  end

  def get_ticket_by_id(ticket_id) do
    NaiveDice.Events.Ticket
    |> NaiveDice.Repo.get(ticket_id)
    |> NaiveDice.Repo.preload([:event])
  end

  def remove_all_tickets() do
    from(t in Ticket, where: t.confirmed == true)
    |> Repo.delete_all()
  end
end

lib/naive_dice_web/controllers/ticket_controller.ex
defmodule NaiveDiceWeb.TicketController do
  use NaiveDiceWeb, :controller
  alias NaiveDice.{Events, Tickets}
  alias NaiveDice.Repo

  action_fallback(NaiveDiceWeb.FallbackController)

  # STEPS OF THE WIZARD

  @doc """
  STEP 1: Renders an empty form with user name input
  That's an entry point for the booking flow.
  """
  def new(conn, %{"event_id" => event_id}) do
    with {:ok, event} <- Events.get_event_by_id(event_id) do
      # TODO: implement this
      remaining_tickets = event.allocation - Tickets.available_tickets(Repo, event)

      render(conn, "new.html", %{
        changeset: Tickets.new_ticket_changeset(event),
        event: event,
        remaining_tickets: remaining_tickets,
        message: get_flash(conn, :message)
      })
    end
  end

  @doc """
  STEP 2: Renders the Stripe payment form
  """
  def edit(conn, %{"id" => ticket_id}) do
    # TODO: implement this
    ticket = Tickets.get_ticket_by_id(ticket_id)

    %{url: url, id: payment_id} = NaiveDice.Stripe.create_session(ticket)

    {:ok, ticket} = Tickets.update_payment_id(ticket, payment_id)
    schedule_ticket_cleanup(ticket)

    render(conn, "edit.html", %{ticket: ticket, checkout_url: url})
  end

  @doc """
  STEP 3: Renders the confirmation / receipt / thank you screen
  """
  def show(conn, %{"id" => ticket_id}) do
    # TODO: don't render a pending ticket as a successfully purchased one
    ticket = Tickets.get_ticket_by_id(ticket_id)

    case ticket.confirmed do
      true -> render(conn, "show.html", %{ticket: ticket})
      _ -> render(conn, "pending.html", %{ticket: ticket})
    end
  end

  # TRANSITIONS BETWEEN WIZARD STEPS

  @doc """
  Reserves a ticket for 5 minutes
  """
  def create(conn, %{"event_id" => event_id, "ticket" => %{"user_name" => user_name}}) do
    with {:ok, event} <- Events.get_event_by_id(event_id) do
      Tickets.reserve_ticket(event, user_name)
      |> redirect_create(conn, event)
    end
  end

  defp redirect_create({:error, :create_ticket, %{errors: errors}, _}, conn, event) do
    message =
      errors
      |> Enum.map(fn {k, v} ->
        {message, _} = v
        "#{k}: #{message}."
      end)
      |> Enum.join("/n")

    conn
    |> put_flash(:message, message)
    |> redirect(to: "/events/#{event.id}/tickets/new")
  end

  defp redirect_create({:error, :check_available_tickets, _, _}, conn, _) do
    render(conn, "sold_out.html")
  end

  defp redirect_create({:ok, %{create_ticket: ticket}}, conn, _) do
    redirect(conn, to: Routes.ticket_path(conn, :edit, ticket.id))
  end

  defp schedule_ticket_cleanup(ticket) do
    expires_in = :timer.minutes(5)
    NaiveDice.TicketScheduler.Supervisor.start_child(%{ticket: ticket, expires_in: expires_in})
  end

  @doc """
  Updates a ticket with the charge details and redirects to the confirmation / receipt / thank you
  """
  def update(conn, %{"session_id" => session_id}) do
    ticket =
      Tickets.get_by_payment_id(session_id)
      |> Repo.preload(:event)

    Tickets.confirm_paid_ticket(ticket)
    |> redirect_show(conn)
  end

  defp redirect_show({:error, :check_available_tickets, _, _}, conn) do
    render(conn, "sold_out_after_checkout.html")
  end

  defp redirect_show({:ok, %{ticket: ticket}}, conn) do
    redirect(conn, to: Routes.ticket_path(conn, :show, ticket.id))
  end

  def cancel(conn, %{"ticket_id" => _ticket_id}) do
    render(conn, "cancel.html")
  end

  # ADMIN ACTIONS

  @doc """
  Helper method which returns the system into the original state (useful for testing)
  """
  def reset_guests(conn, _params) do
    Tickets.remove_all_tickets()

    conn
    |> put_flash(:info, "All tickets deleted. Starting from scratch.")
    |> redirect(to: "/")
  end
end

lib/naive_dice_web/views/ticket_view.ex
defmodule NaiveDiceWeb.TicketView do
  use NaiveDiceWeb, :view
end

lib/naive_dice_web/templates/ticket/edit.html.eex
<!--
Renders a payment form. 
Capturing a payment "updates" the ticket (marks it as a "paid" one).
-->

<div class="all-bold">

    <p>Nice to meet you <%= @ticket.user_name %>!</p>

    <p>
    We reserved your ticket for 5 minutes
    <br>
    Please complete the purchase using a test credit card
    </p>

</div>

<%= if @checkout_url != nil do %>
<%=
    button(
        "Checkout",
        to: @checkout_url,
        method: :get,
        class: "btn btn-primary"
    )
%>
<% else %>
    <p>Sorry, there was a problem while preparing the payment. Try again in some minutes</p>
<% end %>

lib/naive_dice_web/templates/ticket/new.html.eex
<!--
Renders an empty form with user name input. That's an entry point for the booking flow.
-->

<h1>
  DON'T MISS YOUR TICKETS
  <br>
  FOR <%= @event.title %>
</h1>

<p>
only <%= @remaining_tickets %> ticket(s) left
</p>

<br>

<%= form_for @changeset, Routes.event_ticket_path(@conn, :create, @event.id), fn f -> %>
  <%= if @message != nil do %>
    <p>There were some errors:</p>
    <div class="alert alert-primary" role="alert">
      <%= @message %>
    </div>
  <% end %>

  <div class="col-md-6 mb-3">
    <label>YOUR NAME </label>
    <br>
    <%= text_input f, :user_name, required: true, class: "form-control", placeholder: "e.g John Doe" %>

    <br>

    <%= submit "Reserve ticket for 5 minutes", class: "btn btn-primary" %>
  </div>
<% end %>

lib/naive_dice_web/templates/ticket/pending.html.eex
<h1>Dear <%= @ticket.user_name %>,</h1>

<p>
    Your ticket is pending confirmation.
</p>

<br>
<br>
<br>
<br>
<br>

lib/naive_dice_web/templates/ticket/problem.html.eex
<p>
    There was a problem with your callback request
<p>

lib/naive_dice_web/templates/ticket/show.html.eex
<!--
Renders a successfully purchased ticket.
-->

<h1>Congratulations <%= @ticket.user_name %>!</h1>

<p>
    You've been added to the 
    <a href="<%= Routes.guest_path(@conn, :index) %>">list of guests</a>
</p>

<br>
<br>
<br>
<br>
<br>

lib/naive_dice_web/templates/ticket/sold_out.html.eex
<p>
    Tickets have sold out, come back in a few minutes
</p>

lib/naive_dice_web/templates/ticket/sold_out_after_checkout.html.eex
<p>Tickets have sold out. Please contact our team to request a refund</p>